[build]
  publish = "dist/public"
  command = "./netlify.build.sh"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_KEYS = "VITE_FOR4PAYMENTS_SECRET_KEY,FOR4PAYMENTS_SECRET_KEY"
  SECRETS_SCAN_OMIT_PATHS = "dist/public/assets/*"

[[redirects]]
  from = "/vehicle-api/*"
  to = "/.netlify/functions/vehicle-proxy/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"
    
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"